---
# See https://prek.j178.dev for more information.
# yaml-language-server: $schema=https://www.schemastore.org/prek.json
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files

    - repo: https://github.com/betterleaks/betterleaks
      rev: v1.8.1
      hooks:
        - id: betterleaks

    - repo: local
      hooks:
        - id: zizmor
          name: zizmor
          entry: zizmor --offline
          language: system
          files: ^\.github/workflows/.*\.ya?ml$

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.12
      hooks:
        - id: actionlint
